# Generated by Django 4.1.5 on 2023-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_surname', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_surname', models.CharField(max_length=255)),
                ('client_phone', models.IntegerField(max_length=255)),
                ('analysis_name', models.CharField(max_length=255)),
                ('analysis_cathegory', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('norma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_cathegory', models.CharField(max_length=255)),
                ('analysis_name', models.CharField(max_length=255)),
                ('norma', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
