# Generated by Django 4.1.5 on 2023-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал заявок', 'verbose_name_plural': 'Журнал заявок'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайс'},
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='client_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='norma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
