# Generated by Django 4.1.5 on 2023-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_journal_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='is_done',
            field=models.CharField(choices=[('ready', 'Готово'), ('nready', 'Не готово')], default='nready', max_length=10),
        ),
    ]
