# Generated by Django 4.1.5 on 2023-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_journal_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='is_done',
            field=models.CharField(choices=[('Готов', 'Готово'), ('Не готов', 'Не готово')], default='Не готов', max_length=10),
        ),
    ]
