# Generated by Django 4.1.5 on 2023-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_analysis_journal_number_alter_journal_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.RemoveField(
            model_name='journal2',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='analysis_cathegory',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='analysis_name',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='Journal2',
        ),
        migrations.AddField(
            model_name='journal',
            name='analysis_cathegory',
            field=models.ManyToManyField(to='lms.structure'),
        ),
        migrations.AddField(
            model_name='journal',
            name='analysis_name',
            field=models.ManyToManyField(to='lms.price'),
        ),
    ]
