# Generated by Django 4.1.5 on 2023-02-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_structure_remove_journal2_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_surname',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.journal'),
        ),
        migrations.AlterField(
            model_name='price',
            name='analysis_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.structure'),
        ),
    ]
