# Generated by Django 4.1.5 on 2023-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_remove_client_client_name_remove_client_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='analysis_cathegory',
            field=models.ManyToManyField(blank=True, to='lms.structure'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='analysis_name',
            field=models.ManyToManyField(blank=True, to='lms.price'),
        ),
    ]
