# Generated by Django 4.1.5 on 2023-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_journal_analysis_cathegory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='analysis_cathegory',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='analysis_name',
        ),
        migrations.AlterField(
            model_name='journal',
            name='analysis_cathegory',
            field=models.ManyToManyField(to='lms.structure'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='analysis_name',
            field=models.ManyToManyField(to='lms.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
