# Generated by Django 4.1.5 on 2023-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_rename_analysis_cathegory_price_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайс'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='price',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='norma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
