# Generated by Django 4.1.5 on 2023-02-28 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_price_options_alter_structure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='analysis_cathegory',
            field=models.ManyToManyField(to='lms.structure', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='analysis_name',
            field=models.ManyToManyField(to='lms.price', verbose_name='название анализа'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='client_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='client_surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Результат анализов'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_done',
            field=models.CharField(choices=[('Готов', 'Готово'), ('Не готов', 'Не готово')], default='Не готов', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='norma',
            field=models.CharField(blank=True, choices=[('Отрицательно', 'Отрицательно'), ('В норме', 'В норме'), ('Титр меньше 250', 'Титр меньше 250'), ('Титр меньше 150', 'Титр меньше 150'), ('0 - 10', '0 - 10'), ('0 - 13.6', '0 - 13.6'), ('0 - 1', '0 - 1'), ('менее 50', 'менее 50'), ('0.2 - 0.6', '0.2 - 0.6')], max_length=255, null=True, verbose_name='Нормы'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='price',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок готовности'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='price',
            name='norma',
            field=models.CharField(blank=True, choices=[('Отрицательно', 'Отрицательно'), ('В норме', 'В норме'), ('Титр меньше 250', 'Титр меньше 250'), ('Титр меньше 150', 'Титр меньше 150'), ('0 - 10', '0 - 10'), ('0 - 13.6', '0 - 13.6'), ('0 - 1', '0 - 1'), ('менее 50', 'менее 50'), ('0.2 - 0.6', '0.2 - 0.6')], max_length=255, null=True, verbose_name='Нормы'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подразделение'),
        ),
    ]
